### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by Yohn** [barkstone2/vault-to-blog#149]
### Describe the bug

Repo - https://github.com/Yohn/Testing-Obsidian-Vault-to-Blog
Github Page - https://yohn.github.io/Testing-Obsidian-Vault-to-Blog/

When the github repo name is not our `username.github.io` the `/assets/` folder is not loaded since the path is broken

I just installed a fresh copy of vault-to-blog from obsidian community plugins within obsidian

### Relevant errors (if available) from notifications or console (`CTRL+SHIFT+I`)

```shell
14:00:20.537 Navigated to https://yohn.github.io/Testing-Obsidian-Vault-to-Blog/
14:00:20.573 GET
https://yohn.github.io/Testing-Obsidian-Vault-to-Blog/
[HTTP/2 304  133ms]

14:00:20.775 GET
https://yohn.github.io/assets/index-Cnsuih2l.js
NS_ERROR_CORRUPTED_CONTENT

14:00:20.782 GET
https://yohn.github.io/assets/index-CeRC-Nhy.css
[HTTP/2 404  283ms]

14:00:20.980 Loading module from “https://yohn.github.io/assets/index-Cnsuih2l.js” was blocked because of a disallowed MIME type (“text/html”). Testing-Obsidian-Vault-to-Blog
14:00:20.982 Loading failed for the module with source “https://yohn.github.io/assets/index-Cnsuih2l.js”. Testing-Obsidian-Vault-to-Blog:19:71
14:00:21.102 GET
https://yohn.github.io/favicon.ico
[HTTP/2 404  0ms]
```

### Steps to reproduce

Create another repo thats name is not your-username.github.io and install and publish your folder in the vault

### Expected Behavior

Sub directories for vault would be accounted for

### Operating system

Windows

### Obsidian Version

1.6.7

### Plugin version

0.0.2

**Comment by barkstone2** [comment]
Hi there, thank you for suggesting a bug report.

It seems you didn't use the correct repository name.
The repository name for GitHub Pages should be `<username>.github.io`.
Please refer to point 3 in [this documentation](https://docs.github.com/en/pages/getting-started-with-github-pages/creating-a-github-pages-site).

Repo - [https://github.com/barkstone3/barkstone3.github.io](https://github.com/barkstone3/barkstone3.github.io)
GitHub Pages - [https://barkstone3.github.io](https://barkstone3.github.io)

I will add this information to the README.md later.

Thanks.
