### ISSUE TITLE
[BUG] Is the plugin still working after latest Obsidian updates?

### ISSUE THREAD

**Issue by agnoldo** [barkstone2/vault-to-blog#160]
### Describe the bug

Hello, @barkstone2 . Thanks for the amazing idea and all the efforts on the implementation. I would love to use your plugin. Unfortunately I tested it both in Windows and macOS but couldn't be successful.

In Windows, the plugin was downloaded correctly, with all files (react-app) and so on. After activating (also correctly, with Github oauth...), I hit publish and then I get an error "Failed to pushing to remote. There might be no changes to push", and then "src refspec main does not match any".

On mac, the plugin was not downloaded correctly, I don't know why. After a lot of Uninstall/Install, I just copied the plugin folder from Windows over the mac install and finally could get to the same error.

### Steps to reproduce

- install plugin
- create GH repo
- configure plugin (source folder and repo url)
- activate
- create note to be published
- publish (with button in status bar)

### Operating system

macOS

### Obsidian Version

1.7.6

### Plugin version

0.0.3

**Comment by barkstone2** [comment]
Hello, @agnoldo. Thanks for your interest in this plugin.

I have resolved the "src refspec main does not match any" error, and a new version has been released. Please reinstall the plugin before using it.

However, the download issue hasn't fixed yet because i couldn't reproduce the issue on my Mac.

Could you provide additional error logs from the Obsidian console? You can check the console by pressing `CMD + OPTION + I` on Mac.

**Comment by agnoldo** [comment]
Hello @barkstone2 , thanks again, now for your (very very) fast response!

I have already updated the plugin in my Windows machine and got the following errors (first I clicked Activate and then I clicked Publish on one note):

Failed to stage react-app.
Error: spawn ENAMETOOLONG
stageReactApp @ plugin:vault-to-blog:7711
plugin:vault-to-blog:7698 Failed to pushing to remote. There might be no changes to push.
Pushing to https://github.com/agnoldo/agnoldo.github.io
error: src refspec main does not match any
error: failed to push some refs to 'https://github.com/agnoldo/agnoldo.github.io'
---
plugin:vault-to-blog:7650 Failed to stage changes.
fatal: pathspec 'public/sources/.eslintrc.cjs' did not match any files

stageChanges @ plugin:vault-to-blog:7650
plugin:vault-to-blog:7698 Failed to pushing to remote. There might be no changes to push.
Pushing to https://github.com/agnoldo/agnoldo.github.io
error: src refspec main does not match any
error: failed to push some refs to 'https://github.com/agnoldo/agnoldo.github.io'

**Comment by barkstone2** [comment]
Hello @agnoldo, have you reinstalled the plugin?

The issue occurred because the branch name of the react-app directory was not `main`.

To set your branch name to `main`, i recommend reinstalling the plugin.
Alternatively, you can change the branch name manually in {your_vault_path}/.obsidian/plugins/vault-to-blog/react-app/0.0.4/react-app.

**Comment by agnoldo** [comment]
Thanks, @barkstone2 . I have updated the plugin, but not reinstalled (uninstall + install). Doing it right now...

**Comment by agnoldo** [comment]
Unfortunately I have reinstalled and, when activating, I got the following error:

plugin:vault-to-blog:7638 Failed to remove remote.
Error: Git.cwd: cannot change to non-directory "C:\Users\..../.obsidian/plugins/vault-to-blog/react-app/0.0.4/react-app"

I can confirm that the vault-to-blog plugin folder doesn't have react-app subfolder...

This error happened on Windows. I will test on a Mac later.

**Comment by barkstone2** [comment]
Did the activation succeed?

The error message, `Failed to remove remote`, can appeared when the plugin is deactivated by changing the source directory or repository URL, or by clicking the deactivate button.

If the activation succeeded, it is not actually an error. In that case, there is no problem using the plugin.

I know these error messages can confuse users, so I plan to change them to only display necessary messages.
I apologize for any confusion caused.

**Comment by agnoldo** [comment]
Hello @barkstone2 . I tried to Activate again and now it worked beautifully, without any error message. And I can confirm that plugin folder now contains two subfolders: ".git-backup" and "react-app".

Then I hit publish on my note and again no error messages. I checked my repo and ... vòilá!

훌륭한 아이디어와 훌륭한 작업에 박수를 보냅니다. 진심으로 감사드리며 브라질에서 직접 포옹을 보내드립니다.

I hope Google Translate works welll... ;-)

**Comment by barkstone2** [comment]
I'm glad to hear that.

Thanks again for your interest in this plugin. 😄
